---
title: Pueblo Unido PDX
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: jwbentle@gmail.com
description: Pueblo Unido website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:
github_username:  jbentley10

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
